namespace TuningShops.Memory
{
    /// <summary>
    /// Represents the type of mod of a vehicle.
    /// </summary>
    public enum EVehicleModType
    {
        VMT_SPOILER = 0,
        VMT_BUMPER_F = 1,
        VMT_BUMPER_R = 2,
        VMT_SKIRT = 3,
        VMT_EXHAUST = 4,
        VMT_CHASSIS = 5,
        VMT_GRILL = 6,
        VMT_BONNET = 7,
        VMT_WING_L = 8,
        VMT_WING_R = 9,
        VMT_ROOF = 10,
        VMT_PLTHOLDER = 11,
        VMT_PLTVANITY = 12,
        VMT_INTERIOR1 = 13,
        VMT_INTERIOR2 = 14,
        VMT_INTERIOR3 = 15,
        VMT_INTERIOR4 = 16,
        VMT_INTERIOR5 = 17,
        VMT_SEATS = 18,
        VMT_STEERING = 19,
        VMT_KNOB = 20,
        VMT_PLAQUE = 21,
        VMT_ICE = 22,
        VMT_TRUNK = 23,
        VMT_HYDRO = 24,
        VMT_ENGINEBAY1 = 25,
        VMT_ENGINEBAY2 = 26,
        VMT_ENGINEBAY3 = 27,
        VMT_CHASSIS2 = 28,
        VMT_CHASSIS3 = 29,
        VMT_CHASSIS4 = 30,
        VMT_CHASSIS5 = 31,
        VMT_DOOR_L = 32,
        VMT_DOOR_R = 33,
        VMT_LIVERY_MOD = 34,
        VMT_LIGHTBAR = 35,
        VMT_ENGINE = 36,
        VMT_BRAKES = 37,
        VMT_GEARBOX = 38,
        VMT_HORN = 39,
        VMT_SUSPENSION = 40,
        VMT_ARMOUR = 41,
        VMT_NITROUS = 42,
        VMT_TURBO = 43,
        VMT_SUBWOOFER = 44,
        VMT_TYRE_SMOKE = 45,
        VMT_HYDRAULICS = 46,
        VMT_XENON_LIGHTS = 47,
        VMT_WHEELS = 48,
        VMT_WHEELS_REAR_OR_HYDRAULICS = 49,
    }
}
